# Generated by Django 5.1.7 on 2025-03-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="Job",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="post",
            new_name="job",
        ),
    ]
