# Generated by Django 5.1.7 on 2025-03-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_post_job_rename_post_user_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="responsibilities",
            field=models.TextField(
                blank=True, null=True, verbose_name="Основные обязанности"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Оклад",
            ),
        ),
    ]
