# Generated by Django 5.1.7 on 2025-03-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0003_job_responsibilities_job_salary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("create_transfer", "Может создавать перемещения"),
                    ("accept_transfer", "Может принимать перемещения"),
                    ("accept_supply", "Может принимать поставки"),
                    ("create_inventory", "Может создавать инвентаризацию"),
                    ("confirm_inventory", "Может подтверждать инвентаризацию"),
                    ("create_write_off", "Может создавать списания на брак"),
                    ("confirm_write_off", "Может подтверждать списания на брак"),
                    ("edit_product", "Может редактировать товары"),
                    ("create_sale", "Может создавать продажи"),
                    ("cancel_sale", "Может отменять продажи"),
                    ("process_return", "Может обрабатывать возвраты"),
                    ("edit_supplier", "Может редактировать поставщиков"),
                    ("manage_users", "Может управлять пользователями"),
                    ("manage_roles", "Может управлять ролями и правами доступа"),
                ],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="job",
            options={
                "ordering": ["title"],
                "verbose_name": "Должность",
                "verbose_name_plural": "Должности",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["username"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.RemoveField(
            model_name="category",
            name="accept_supply",
        ),
        migrations.RemoveField(
            model_name="category",
            name="accept_transfer",
        ),
        migrations.RemoveField(
            model_name="category",
            name="cancel_sale",
        ),
        migrations.RemoveField(
            model_name="category",
            name="confirm_inventory",
        ),
        migrations.RemoveField(
            model_name="category",
            name="confirm_write_off",
        ),
        migrations.RemoveField(
            model_name="category",
            name="create_inventory",
        ),
        migrations.RemoveField(
            model_name="category",
            name="create_sale",
        ),
        migrations.RemoveField(
            model_name="category",
            name="create_transfer",
        ),
        migrations.RemoveField(
            model_name="category",
            name="create_write_off",
        ),
        migrations.RemoveField(
            model_name="category",
            name="edit_product",
        ),
        migrations.RemoveField(
            model_name="category",
            name="edit_supplier",
        ),
        migrations.RemoveField(
            model_name="category",
            name="manage_roles",
        ),
        migrations.RemoveField(
            model_name="category",
            name="manage_users",
        ),
        migrations.RemoveField(
            model_name="category",
            name="process_return",
        ),
        migrations.AddField(
            model_name="category",
            name="permissions",
            field=models.ManyToManyField(
                blank=True, to="auth.permission", verbose_name="Права"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
    ]
