# Generated by Django 5.1.7 on 2025-03-15 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_category_options_alter_job_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Job",
            new_name="Position",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "permissions": (
                    ("create_transfer", "Может создавать перемещения"),
                    ("accept_transfer", "Может принимать перемещения"),
                    ("accept_supply", "Может принимать поставки"),
                    ("create_inventory", "Может создавать инвентаризацию"),
                    ("confirm_inventory", "Может подтверждать инвентаризацию"),
                    ("create_write_off", "Может создавать списания на брак"),
                    ("confirm_write_off", "Может подтверждать списания на брак"),
                    ("edit_product", "Может редактировать товары"),
                    ("create_sale", "Может создавать продажи"),
                    ("cancel_sale", "Может отменять продажи"),
                    ("process_return", "Может обрабатывать возвраты"),
                    ("edit_supplier", "Может редактировать поставщиков"),
                    ("manage_users", "Может управлять пользователями"),
                    ("manage_roles", "Может управлять ролями и правами доступа"),
                ),
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.RenameField(
            model_name="user",
            old_name="job",
            new_name="position",
        ),
    ]
