# Generated by Django 5.1.7 on 2025-03-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0005_rename_job_position_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="EmployeeCategory",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="category",
            new_name="employee_category",
        ),
    ]
