# Generated by Django 5.1.7 on 2025-03-21 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_employeecategory_options_user_employee_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["username"],
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
    ]
