services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=Inventory
      - POSTGRES_USER=sliva
      - POSTGRES_PASSWORD=241655
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  base_workspace:
    build:
      context: ..
      dockerfile: .docker/dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/Inventory_Management
    env_file:
      - ../.env
    restart: unless-stopped

volumes:
  postgres_data: