# Generated by Django 5.1.7 on 2025-03-23 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_price_purchase_price_alter_price_selling_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movement",
            name="product",
        ),
        migrations.RemoveField(
            model_name="movement",
            name="user",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="product",
        ),
    ]
