# Generated by Django 5.1.7 on 2025-03-23 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_movement_product_remove_movement_user_and_more"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warehouse.supplier",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AlterModelOptions(
            name="brand",
            options={"verbose_name": "Бренд", "verbose_name_plural": "Бренды"},
        ),
        migrations.DeleteModel(
            name="Movement",
        ),
        migrations.DeleteModel(
            name="Stock",
        ),
        migrations.DeleteModel(
            name="Supplier",
        ),
    ]
